"use client";

import { useState, type FormEvent } from "react";
import Link from "next/link";
import { ArrowRight, ArrowUpRight, Check, Flower2, Gift, Heart, Leaf, Plus, RotateCcw, Ruler, Sun, Truck } from "lucide-react";
import { bebeCategories, bebeCollections, type BebeCategory, type BebeCollection } from "@/lib/bebe-products";
import { useLocale } from "./locale-provider";
import { DemoDialog } from "./demo-dialog";
import { ProductArt } from "./bebe-product-art";

export function BebeSections({ browseCategory, browseCollection, openGuide }: { browseCategory: (value: BebeCategory) => void; browseCollection: (value: BebeCollection) => void; openGuide: () => void }) {
  const { locale } = useLocale();
  const t = (vi: string, en: string) => locale === "en" ? en : vi;
  const [article, setArticle] = useState<number | null>(null);
  const [subscribed, setSubscribed] = useState(false);
  const articles = [
    { title: t("Chọn size để bé thoải mái lớn lên", "A little room to grow"), label: t("CHỌN SIZE", "SIZE NOTES"), icon: Ruler, body: t("Đo chiều cao của bé khi đứng thẳng, rồi đối chiếu bảng size của từng sản phẩm. Với bé sơ sinh, hãy đo chiều dài khi bé nằm thoải mái. Độ tuổi là gợi ý; chiều cao và số đo thực tế sẽ hữu ích hơn. Nếu bé nằm giữa hai size, cân nhắc phom dáng và mức độ rộng mong muốn.", "Measure your child's standing height and compare it with the product's size chart. For babies, measure their length while lying comfortably. Age is a guide; actual measurements are more useful. Between sizes, consider the garment's fit and how much room you prefer."), detail: t("M = tháng, Y = tuổi. Bảng size trong cửa hàng mẫu là số đo tham khảo; khi triển khai bán hàng cần dùng bảng đo của nhà sản xuất.", "M = months, Y = years. Charts in this demo are illustrative; a live store should use the manufacturer's measurements.") },
    { title: t("Giữ những chiếc áo luôn mềm mại", "Keep their favourites soft"), label: t("CHĂM ĐỒ CHO BÉ", "CLOTHING CARE"), icon: Leaf, body: t("Phân loại màu trước khi giặt và đọc nhãn chăm sóc của từng món. Ưu tiên chu trình giặt nhẹ cho chất liệu cotton, muslin và đồ dệt kim. Phơi ở nơi thoáng, tránh nắng gắt để màu sắc giữ được vẻ dịu dàng.", "Separate colours and read the care label on each piece. Choose a gentle wash for cotton, muslin, and knitwear. Air-dry away from strong direct sunlight to keep colours looking soft."), detail: t("Với cardigan, sửa lại phom khi còn ẩm và phơi nằm. Cất quần áo khi đã khô hoàn toàn.", "Reshape knitwear while damp and dry it flat. Always make sure clothes are completely dry before storing them.") },
    { title: t("Một tủ đồ nhỏ, thật nhiều cách phối", "A small wardrobe, many adventures"), label: t("PHỐI ĐỒ", "LITTLE OUTFITS"), icon: Sun, body: t("Bắt đầu với vài chiếc áo thun dễ phối, một chiếc quần short và một bộ yếm. Chọn các sắc kem, xanh dịu và vàng bơ để bé tự kết hợp. Thêm mũ bucket cho buổi dạo chơi, balo nhỏ cho ngày đến lớp.", "Start with a few easy tees, a pair of shorts, and dungarees. Cream, soft green, and butter yellow mix happily together. Add a bucket hat for a day out or a little backpack for school."), detail: t("Không cần mọi món đều cùng màu. Một họa tiết sọc hoặc ô caro sẽ làm bộ đồ của bé thêm vui.", "Everything doesn't have to match. A stripe or a little gingham can bring a playful outfit together.") },
  ];
  function subscribe(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubscribed(true); }

  return <>
    <section className="bebe-collections bebe-shell" id="collections"><div className="bebe-section-title"><div><span className="bebe-eyebrow">LITTLE OUTFITS, BIG MOMENTS</span><h2>{t("Mỗi ngày, một chút đáng yêu.", "A little lovely, every day.")}</h2></div><Flower2 className="bebe-title-flower" size={45} /></div><div className="bebe-collection-grid">{bebeCollections.map(item => <button key={item.id} className={`bebe-collection-card ${item.color}`} onClick={() => browseCollection(item.id)}><span className="bebe-eyebrow">{item.eyebrow}</span><div className="bebe-collection-art"><ProductArt id={item.images[0]} /><ProductArt id={item.images[1]} /></div><div><h3>{item.name[locale]}</h3><span><ArrowUpRight size={22} /></span></div><p>{item.description[locale]}</p></button>)}</div></section>
    <section className="bebe-gift bebe-shell" id="gifts"><div className="bebe-gift-visual"><div className="bebe-gift-sticker"><Gift size={25} /><span>WITH LOVE,<br />FROM BEBÉ</span></div><ProductArt id={0} /><ProductArt id={3} /><ProductArt id={14} /><span className="bebe-gift-ribbon">a tiny bundle of joy</span></div><div className="bebe-gift-copy"><span className="bebe-eyebrow">WRAPPED IN A LITTLE LOVE</span><h2>{t("Quà nhỏ xinh.", "Tiny little gifts.")}<br /><em>{t("Thương thật nhiều.", "A whole lot of love.")}</em></h2><p>{t("Mừng bé chào đời, sinh nhật đầu tiên hay đơn giản là “cô thương con”. Chọn những món bạn thích, Bebé có thêm lựa chọn gói quà và lời nhắn riêng trong giỏ hàng.", "A new arrival, a first birthday, or simply a little ‘I love you’. Pick their favourites, then add gift wrapping and a personal note in your bag.")}</p><ul><li><Check size={16} />{t("Tự chọn quà theo độ tuổi của bé", "Choose pieces for their age")}</li><li><Check size={16} />{t("Gói quà thêm 25.000đ / đơn", "Gift wrapping: ₫25,000 per order")}</li><li><Check size={16} />{t("Thiệp với lời nhắn của riêng bạn", "A card with your personal message")}</li></ul><button className="bebe-cta" onClick={() => browseCollection("welcome")}>{t("Chọn quà cho bé", "Build a little gift")} <Gift size={18} /></button></div></section>
    <section className="bebe-story bebe-shell" id="story"><div><span className="bebe-eyebrow">A NOTE FROM BEBÉ</span><h2>{t("Tuổi thơ chỉ có một lần.", "They’re only little once.")}<br /><em>{t("Cứ để bé là bé.", "Let them be little.")}</em></h2></div><div><p>{t("Một vệt màu trên áo, đầu gối lấm đất, tiếng cười giòn tan. Với Bebé, một bộ đồ đẹp là bộ đồ để bé thoải mái làm tất cả những điều ấy.", "Paint on a sleeve, muddy knees, and a very big laugh. To us, a lovely outfit is one that lets them do all of that.")}</p><p>{t("Chúng mình yêu chất liệu mềm, phom dáng dễ vận động và những màu sắc nhìn là thấy vui. Những món đồ nhỏ, đồng hành cùng một tuổi thơ thật lớn.", "We love soft textures, room to move, and colours that make you smile. Little clothes, made to be part of a very big childhood.")}</p><span className="bebe-signature">with love, bebé <Heart size={17} /></span></div></section>
    <div className="bebe-service-grid bebe-shell">{[{ icon: Leaf, title: t("Mềm mại mỗi ngày", "Soft every day"), copy: t("Cotton, muslin và những chất liệu dễ mặc.", "Cotton, muslin, and easy everyday textures.") }, { icon: Truck, title: t("Giao hàng tận nơi", "Delivered with care"), copy: t("Miễn phí giao hàng từ 699.000đ.", "Free shipping on orders over ₫699,000.") }, { icon: RotateCcw, title: t("Đổi size dễ dàng", "Easy size exchanges"), copy: t("Trong 14 ngày, sản phẩm còn nguyên nhãn.", "Within 14 days, with original tags attached.") }, { icon: Gift, title: t("Gửi thêm yêu thương", "Send a little love"), copy: t("Thêm gói quà và lời nhắn trong giỏ hàng.", "Add gift wrap and a note in your bag.") }].map(({ icon: Icon, title, copy }) => <div key={title}><Icon size={27} /><h3>{title}</h3><p>{copy}</p></div>)}</div>
    <section className="bebe-journal bebe-shell" id="journal"><div className="bebe-section-title"><div><span className="bebe-eyebrow">THE LITTLE JOURNAL</span><h2>{t("Một góc nhỏ cho ba mẹ.", "A little corner for parents.")}</h2></div><span>{t("Chọn đồ nhẹ nhàng hơn, mỗi ngày.", "Making everyday choices a little easier.")}</span></div><div className="bebe-journal-grid">{articles.map((item, index) => <button key={item.label} onClick={() => setArticle(index)}><div className={`bebe-journal-art tone-${index}`}><item.icon size={57} strokeWidth={1.2} /><span>0{index + 1}</span></div><small>{item.label} · {t("2 PHÚT ĐỌC", "2 MIN READ")}</small><h3>{item.title}</h3><span>{t("Đọc cùng Bebé", "Read with Bebé")} <ArrowUpRight size={17} /></span></button>)}</div></section>
    <section className="bebe-faq bebe-shell" id="faq"><div><span className="bebe-eyebrow">A LITTLE HELP</span><h2>{t("Ba mẹ hay hỏi…", "Little questions…")}</h2><p>{t("Một vài điều nhỏ trước khi sắm đồ cho bé.", "A few things to know before you shop.")}</p><button className="bebe-text-link" onClick={openGuide}><Ruler size={17} />{t("Mở bảng size tham khảo", "Open the size guide")}</button></div><div>{[
      [t("Bé nằm giữa hai size thì chọn thế nào?", "What if my child is between sizes?"), t("Ưu tiên đối chiếu chiều cao với bảng size của sản phẩm, sau đó cân nhắc độ rộng bé thấy thoải mái. Độ tuổi chỉ là thông tin tham khảo.", "Start with their height and the product's size chart, then consider how much room feels comfortable. Age is a guide only.")],
      [t("Mình có thể đổi size không?", "Can I exchange a size?"), t("Chính sách minh họa: hỗ trợ đổi size trong 14 ngày với sản phẩm chưa sử dụng, chưa giặt và còn nguyên nhãn. Khi triển khai cửa hàng thật, thông tin giao nhận và phí đổi sẽ được xác nhận theo đơn.", "Sample policy: size exchanges within 14 days for unworn, unwashed items with original tags. A live store would confirm shipping details and any exchange costs per order.")],
      [t("Có thể gửi quà kèm lời nhắn không?", "Can I include a gift message?"), t("Có nhé! Trong giỏ hàng, bật gói quà và nhập lời nhắn tối đa 180 ký tự. Phí gói quà minh họa là 25.000đ cho cả đơn.", "Yes! Choose gift wrapping in your bag and write a note of up to 180 characters. The demo gift-wrap fee is ₫25,000 per order.")],
      [t("Đây có phải cửa hàng bán hàng thật không?", "Is this a live shop?"), t("Đây là giao diện mẫu của DevDes. Sản phẩm, giá và chính sách dùng để minh họa; giỏ hàng, yêu thích và đăng ký chỉ hoạt động trong phiên xem, không gửi đơn hay thu tiền.", "This is a DevDes demo storefront. Products, prices, and policies are illustrative. Your bag, favourites, and signup are session-only; no orders are sent and no payment is taken.")],
    ].map(([question, answer]) => <details key={question}><summary>{question}<Plus size={17} /></summary><p>{answer}</p></details>)}</div></section>
    <section className="bebe-newsletter"><Flower2 size={45} /><div><span className="bebe-eyebrow">LET&apos;S GROW TOGETHER</span><h2>{t("Nhận một chút dễ thương.", "A little lovely in your inbox.")}</h2><p>{t("Bộ sưu tập mới và những gợi ý nhỏ từ Bebé.", "New little collections and thoughtful notes from Bebé.")}</p></div><form onSubmit={subscribe}><label className="bebe-sr-only" htmlFor="bebe-email">Email</label><div><input id="bebe-email" type="email" placeholder={t("Email của ba mẹ", "Your email address")} required onChange={() => setSubscribed(false)} /><button type="submit" aria-label={t("Đăng ký nhận tin", "Subscribe")}><ArrowRight size={22} /></button></div><small role="status">{subscribed ? t("Đã thử đăng ký thành công! Bản mẫu không lưu hoặc gửi email.", "Demo signup complete! No email is stored or sent.") : t("Đăng ký minh họa · Không gửi email thực tế.", "Demo signup · No real emails are sent.")}</small></form></section>
    <footer className="bebe-footer"><div className="bebe-footer-main bebe-shell"><div><a className="bebe-logo" href="#top">bebé<span>BOUTIQUE · LITTLE & LOVED</span></a><p>{t("Những món đồ nhỏ.\nMột tuổi thơ thật lớn.", "Little things.\nA wonderfully big childhood.")}</p><span className="bebe-footer-flower"><Flower2 /><Sun /><Heart /></span></div><div><h3>{t("Đồ xinh cho bé", "Shop little things")}</h3>{bebeCategories.map(item => <button key={item.id} onClick={() => browseCategory(item.id)}>{item.label[locale]}</button>)}</div><div><h3>{t("Cùng Bebé", "With Bebé")}</h3><a href="#collections">{t("Bộ sưu tập", "Collections")}</a><a href="#gifts">{t("Quà tặng", "Little gifts")}</a><a href="#story">{t("Câu chuyện Bebé", "Our story")}</a><a href="#journal">{t("Góc ba mẹ", "The little journal")}</a></div><div><h3>{t("Ba mẹ cần biết", "Here to help")}</h3><button onClick={openGuide}>{t("Bảng size", "Size guide")}</button><a href="#faq">{t("Giao hàng & đổi size", "Delivery & exchanges")}</a><a href="#faq">{t("Câu hỏi thường gặp", "Little questions")}</a><Link href="/giao-dien">{t("Khám phá mẫu DevDes", "Explore DevDes templates")} ↗</Link></div></div><div className="bebe-footer-bottom bebe-shell"><span>© 2026 Bebé Boutique · {t("Giao diện cửa hàng trẻ em minh họa", "Children’s boutique demo")}</span><span>MADE FOR LITTLE HAPPY HUMANS ♡</span></div></footer>
    {article !== null && <DemoDialog title={articles[article].title} onClose={() => setArticle(null)}><div className="bebe-article"><span className="bebe-eyebrow">THE LITTLE JOURNAL / {articles[article].label}</span><p>{articles[article].body}</p><p>{articles[article].detail}</p><button className="bebe-cta" onClick={() => { setArticle(null); if (article === 0) openGuide(); else browseCategory("all"); }}>{article === 0 ? t("Mở bảng size", "Open size guide") : t("Chọn đồ cùng Bebé", "Shop with Bebé")} <ArrowRight size={18} /></button></div></DemoDialog>}
  </>;
}
