export type TemplateCategory = "rental" | "hotel" | "management" | "advertising";

export type TemplateItem = {
  slug: string;
  category: TemplateCategory;
  categoryLabel: string;
  name: string;
  tagline: string;
  description: string;
  style: string;
  tone: string;
  accent: string;
  dark: string;
  image: string;
  features: string[];
};

export const categories = [
  { id: "all", label: "Tất cả", count: 12 },
  { id: "rental", label: "Dịch vụ cho thuê", count: 3 },
  { id: "hotel", label: "Khách sạn", count: 3 },
  { id: "management", label: "Phần mềm quản lý", count: 3 },
  { id: "advertising", label: "Website quảng cáo", count: 3 },
] as const;

export const templates: TemplateItem[] = [
  {
    slug: "ridenow-car-rental",
    category: "rental",
    categoryLabel: "Dịch vụ cho thuê",
    name: "RideNow",
    tagline: "Thuê xe. Đi bất cứ đâu.",
    description: "Website thuê xe thể thao với trải nghiệm đặt xe nhanh, trẻ và mạnh mẽ.",
    style: "Thể thao / Tương phản",
    tone: "#f4ff3d",
    accent: "#111111",
    dark: "#111111",
    image: "https://images.unsplash.com/photo-1494976388531-d1058494cdd8?auto=format&fit=crop&w=1600&q=85",
    features: ["Tìm xe theo ngày", "Bảng giá trực quan", "Đặt xe nhanh"],
  },
  {
    slug: "nestly-home-rental",
    category: "rental",
    categoryLabel: "Dịch vụ cho thuê",
    name: "Nestly",
    tagline: "Một căn nhà, ngàn trải nghiệm.",
    description: "Nền tảng thuê căn hộ phong cách ấm áp, thân thiện và đầy cảm hứng.",
    style: "Lifestyle / Ấm áp",
    tone: "#f1e8dc",
    accent: "#9f5b3f",
    dark: "#283329",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1600&q=85",
    features: ["Khám phá địa điểm", "Lịch trống", "Đánh giá khách thuê"],
  },
  {
    slug: "gearup-equipment-rental",
    category: "rental",
    categoryLabel: "Dịch vụ cho thuê",
    name: "GearUp",
    tagline: "Đúng thiết bị. Đúng thời điểm.",
    description: "Website cho thuê thiết bị công trình với giao diện công nghiệp, chắc chắn.",
    style: "Công nghiệp / Đậm",
    tone: "#ff6b00",
    accent: "#ff6b00",
    dark: "#171717",
    image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=1600&q=85",
    features: ["Danh mục thiết bị", "Yêu cầu báo giá", "Theo dõi đơn thuê"],
  },
  {
    slug: "aurelia-luxury-hotel",
    category: "hotel",
    categoryLabel: "Khách sạn",
    name: "Aurelia",
    tagline: "Nghỉ dưỡng theo cách riêng.",
    description: "Giao diện resort cao cấp, giàu khoảng thở với trải nghiệm đặt phòng sang trọng.",
    style: "Luxury / Editorial",
    tone: "#e7ddcb",
    accent: "#a78152",
    dark: "#18211b",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1600&q=85",
    features: ["Đặt phòng trực tuyến", "Trải nghiệm nghỉ dưỡng", "Ưu đãi theo mùa"],
  },
  {
    slug: "sunday-boutique-hotel",
    category: "hotel",
    categoryLabel: "Khách sạn",
    name: "Sunday House",
    tagline: "Ở lại lâu hơn một chút.",
    description: "Khách sạn boutique trẻ trung với màu sắc vui tươi và bố cục phá cách.",
    style: "Boutique / Playful",
    tone: "#ffd5dc",
    accent: "#eb4f74",
    dark: "#193a37",
    image: "https://images.unsplash.com/photo-1611892440504-42a792e24d32?auto=format&fit=crop&w=1600&q=85",
    features: ["Gallery phòng", "Local guide", "Đặt phòng nhanh"],
  },
  {
    slug: "hush-minimal-hotel",
    category: "hotel",
    categoryLabel: "Khách sạn",
    name: "Hush",
    tagline: "Không gian để thở.",
    description: "Website khách sạn tối giản kiểu Nhật, tĩnh lặng và tập trung vào hình ảnh.",
    style: "Minimal / Zen",
    tone: "#e8e5de",
    accent: "#5d6c62",
    dark: "#2d302d",
    image: "https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=1600&q=85",
    features: ["Danh sách phòng", "Không gian & tiện ích", "Form đặt phòng"],
  },
  {
    slug: "orbit-crm-dashboard",
    category: "management",
    categoryLabel: "Phần mềm quản lý",
    name: "Orbit CRM",
    tagline: "Mọi khách hàng. Một nơi.",
    description: "Dashboard CRM hiện đại giúp đội sales theo dõi pipeline và hiệu suất tức thời.",
    style: "SaaS / Dark mode",
    tone: "#15172b",
    accent: "#7c6cff",
    dark: "#10111e",
    image: "",
    features: ["Sales pipeline", "Báo cáo realtime", "Quản lý khách hàng"],
  },
  {
    slug: "flowdesk-project-management",
    category: "management",
    categoryLabel: "Phần mềm quản lý",
    name: "Flowdesk",
    tagline: "Công việc trôi, team tiến tới.",
    description: "Ứng dụng quản lý dự án sạch sẽ, sáng sủa và dễ làm quen cho mọi đội nhóm.",
    style: "Clean / Productivity",
    tone: "#e8f2ff",
    accent: "#2877f0",
    dark: "#172133",
    image: "",
    features: ["Kanban board", "Quản lý tiến độ", "Lịch công việc"],
  },
  {
    slug: "minto-store-management",
    category: "management",
    categoryLabel: "Phần mềm quản lý",
    name: "Minto",
    tagline: "Cửa hàng gọn. Kinh doanh khỏe.",
    description: "Phần mềm quản lý bán hàng với dashboard thân thiện và dữ liệu dễ đọc.",
    style: "Friendly / Data",
    tone: "#dff7e9",
    accent: "#188f62",
    dark: "#17342a",
    image: "",
    features: ["Doanh thu", "Kho hàng", "Đơn hàng đa kênh"],
  },
  {
    slug: "loud-creative-agency",
    category: "advertising",
    categoryLabel: "Website quảng cáo",
    name: "LOUD!",
    tagline: "Thương hiệu phải được nhìn thấy.",
    description: "Website creative agency táo bạo, typography lớn và chuyển động đầy năng lượng.",
    style: "Brutal / Bold",
    tone: "#ff4d2e",
    accent: "#ff4d2e",
    dark: "#131313",
    image: "https://images.unsplash.com/photo-1542744094-3a31f272c490?auto=format&fit=crop&w=1600&q=85",
    features: ["Showcase chiến dịch", "Case study", "Form nhận brief"],
  },
  {
    slug: "halo-digital-marketing",
    category: "advertising",
    categoryLabel: "Website quảng cáo",
    name: "Halo Digital",
    tagline: "Tăng trưởng có chiến lược.",
    description: "Landing page digital marketing theo phong cách công nghệ và định hướng chuyển đổi.",
    style: "Tech / Gradient",
    tone: "#dffaff",
    accent: "#4e5bff",
    dark: "#0c1024",
    image: "",
    features: ["Dịch vụ marketing", "Số liệu tăng trưởng", "Đăng ký tư vấn"],
  },
  {
    slug: "muse-brand-studio",
    category: "advertising",
    categoryLabel: "Website quảng cáo",
    name: "Muse Studio",
    tagline: "Ý tưởng đáng để lan truyền.",
    description: "Portfolio studio thương hiệu mang tinh thần tạp chí, thanh lịch và khác biệt.",
    style: "Editorial / Artistic",
    tone: "#f3ead8",
    accent: "#d3342f",
    dark: "#242018",
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1600&q=85",
    features: ["Portfolio dự án", "Giới thiệu studio", "Đặt lịch trao đổi"],
  },
];

export function getTemplate(slug: string) {
  return templates.find((template) => template.slug === slug);
}
